// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkiA5DaLayp8fzXCt5pZZxsaezNSygqlc',
    appId: '1:420150600127:web:752463b2cb3cd5cc94410a',
    messagingSenderId: '420150600127',
    projectId: 'grocary-app-3796a',
    authDomain: 'grocary-app-3796a.firebaseapp.com',
    storageBucket: 'grocary-app-3796a.firebasestorage.app',
    measurementId: 'G-3GFZRGY4X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-uyj4DeJDASjDBnk1ig5AkLdViFUFc8',
    appId: '1:420150600127:android:4a751629cbad837e94410a',
    messagingSenderId: '420150600127',
    projectId: 'grocary-app-3796a',
    storageBucket: 'grocary-app-3796a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKQaxWu4zEva-JXuRNWEloOhgM0m8COk',
    appId: '1:420150600127:ios:7015ca689183c04194410a',
    messagingSenderId: '420150600127',
    projectId: 'grocary-app-3796a',
    storageBucket: 'grocary-app-3796a.firebasestorage.app',
    iosBundleId: 'com.example.onlineGroceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKQaxWu4zEva-JXuRNWEloOhgM0m8COk',
    appId: '1:420150600127:ios:7015ca689183c04194410a',
    messagingSenderId: '420150600127',
    projectId: 'grocary-app-3796a',
    storageBucket: 'grocary-app-3796a.firebasestorage.app',
    iosBundleId: 'com.example.onlineGroceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkiA5DaLayp8fzXCt5pZZxsaezNSygqlc',
    appId: '1:420150600127:web:9a59a29433c758b494410a',
    messagingSenderId: '420150600127',
    projectId: 'grocary-app-3796a',
    authDomain: 'grocary-app-3796a.firebaseapp.com',
    storageBucket: 'grocary-app-3796a.firebasestorage.app',
    measurementId: 'G-C4RN7MY7TW',
  );
}
